name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment-marker:
    runs-on: ubuntu-latest
    steps:
      - name: Create deployment marker
        env:
          API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          GH_USER: ${{ github.event.pusher.name }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          TIME: ${{ github.event.head_commit.timestamp }}
        run: |
          curl -X POST "https://api.newrelic.com/v2/applications/1357353372/deployments.json" \
               -H "Api-Key:$API_KEY" \
               -i \
               -H "Content-Type: application/json" \
               -d \
          "{
            \"deployment\": {
              \"revision\": \"REVISION\",
              \"changelog\": \"$COMMIT_MSG\",
              \"description\": \"$COMMIT_MSG\",
              \"user\": \"$GH_USER\",
              \"timestamp\": \"$TIME\"
            }
          }"
